## ECR image and tag##
image: "307156039661.dkr.ecr.eu-west-1.amazonaws.com/ms-api-global"
tag: "web.a760737"
#command: ["./bin/ms_admin_web"]
#args: ["foreground"]

#app env
env:
  HOST: "admin.mastercardglobal.co"
  PORT: "4000"
  DB_HOSTNAME: "moneysend-global.cpncrvhv2z7u.us-west-2.rds.amazonaws.com"
  DB_USERNAME: "moneysend"
  DB_USERPWD: "AjhYPPX7m8qFHChp"

# Update strategy
rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

# Number of replicas
replicas: 1

#App name
name: web-api

#Health check url
#path: "/health"

#IngressRoute
HOST: "Host(`admin.mastercardglobal.co`)"
