## ECR image and tag##
image: "307156039661.dkr.ecr.eu-west-1.amazonaws.com/web-global"
tag: "co_branded.28d2814"

#app env
env:
  API_HOST: "https://branded-api.mastercardglobal.co"
  CLIENT_ID: 34703003
  HOSTNAME: "test.co"
  MP_HOST: "https://ui.masterpassturkiye.com"
  PORT: "8080"
  THEME: "CO_BRANDED"

# Update strategy
rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

# Number of replicas
replicas: 1

#App name
name: web-co-branded

#Health check url
#path: "/"

#IngressRoute
TLS_NAME: tls-co-branded
HOST: "Host(`test.co`)"
