## ECR image and tag##
image: "307156039661.dkr.ecr.eu-west-1.amazonaws.com/web-global"
tag: "ANYBANK.35ba4e5"

#app env
env:
  API_HOST: "https://branded-api.mastercardglobal.co"
  CLIENT_ID: 34703003
  HOSTNAME: "anybank.co"
  MP_HOST: "https://ui.masterpassturkiye.com"
  PORT: "8080"
  THEME: "ANYBANK"

# Update strategy
rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

# Number of replicas
replicas: 1

#App name
name: web-anybank

#Health check url
#path: "/"

#IngressRoute
TLS_NAME: tls-anybank
HOST: "Host(`anybank.co`)"
