## ECR image and tag##
image: "307156039661.dkr.ecr.eu-west-1.amazonaws.com/web-global"
tag: "simple_portal.51202c6"
#command: [""]
#args: [""]

#app env
env:
  API_HOST: "https://branded-api.mastercardglobal.co"
  CLIENT_ID: 34703003
  HOSTNAME: "simple.mastercardglobal.co"
  MP_HOST: "https://ui.masterpassturkiye.com"
  PORT: "8080"
  THEME: "SIMPLE_PORTAL"

# Update strategy
rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

# Number of replicas
replicas: 1

#App name
name: web-simple-portal

#Health check url
#path: "/"

#IngressRoute
HOST: "Host(`simple.mastercardglobal.co`)"
