## ECR image and tag##
image: "307156039661.dkr.ecr.eu-west-1.amazonaws.com/web-global"
tag: "MC.0.0.1"

#app env
env:
  API_HOST: "https://ms-global.edenlab.com.ua"
  CLIENT_ID: 34703003
  HOSTNAME: "branded-mc.mastercardglobal.co"
  MP_HOST: "https://ui.masterpassturkiye.com"
  PORT: "8080"
  THEME: "MC_BRANDED"

# Update strategy
rollingUpdate:
    maxSurge: "1"
    maxUnavailable: "0"

# Number of replicas
replicas: 1

#App name
name: web-mc

#Health check url
#path: "/"

#IngressRoute
HOST: "Host(`branded-mc.mastercardglobal.co`)"
