{{- if eq .Values.name "api" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-ig
spec:
  entryPoints:
    # - web
    - websecure
  routes:
  - match: "Host(`branded-api.mastercardglobal.co`)"
    kind: Rule
    services:
    - name: api-mc-svc
      port: 80
  tls:
    secretName: tls-1
     {{ end }}
