apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}-svc
  labels:
    app: {{ .Values.name}}
spec:
  ports:
  - port: {{ .Values.env.PORT}}
    targetPort: {{ .Values.env.PORT}}
    protocol: TCP
  selector:
    app: {{ .Values.name}}
  type: ClusterIP
